### ISSUE TITLE
Routing improvements

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#39]
1. Rotating servo connector would improve routing.
![image](https://user-images.githubusercontent.com/1595938/198376519-62f2644a-cde9-417e-a188-325da8c50cd6.png)
\
![image](https://user-images.githubusercontent.com/1595938/198376852-38a053b0-ed4d-4a0d-81ef-30a6a22cb42d.png)

2. Thrower and servo signals could be swapped to get rid of 2 vias in servo signal.
![image](https://user-images.githubusercontent.com/1595938/198377315-b46f8980-de27-47b6-907b-bf1013fd44ec.png)

**Comment by ReikoR** [comment]
On the MCU side, try to route mostly on top layer, so that there is more room for (3.3V) current to flow. Right now current (indicated with yellow lines) has to go through narrow gaps or around traces.
![image](https://user-images.githubusercontent.com/1595938/198831030-d9eed8ce-2c3c-4bab-89f6-faf1dd67a118.png)

**Comment by AnishShr** [comment]
<img width="524" alt="trace_back_copper" src="https://user-images.githubusercontent.com/62991158/198898600-c8f0b804-b0b1-47db-8688-9e8d627bcb6f.PNG">

Is this much routing in the back copper considerable?

I possibly cannot route these traces in front copper because of the component's arrange arrangement and orientation.

**Comment by AnishShr** [comment]
New design with minimal routing (as minimum as possible) in back copper layer in the uC side updated.

**Comment by ReikoR** [comment]
New routing is better.
